{
  # robot configurations, 0->right 1->left
  # comment out robot #1 if only using 1 arm
  "robots": [
    {
      "robot_type": "franka",       # "robot_type": "ur5e",
      "robot_ip": "192.168.1.167",    # "robot_ip": "192.168.0.8",
      "robot_obs_latency": 0.0001,  # 机器人感知延迟 
      "robot_action_latency": 0.1,  # 机器人动作延迟
      "tcp_offset": 0.235,          # 工具中心点（TCP）的偏移量
      # table height for finger-table collision avoidance
      # -inf to disable
      "height_threshold": -0.024,   # 指尖与桌面碰撞避免的阈值
      # sphere collision primitive size and location for inter-gripper collision avoidance
      # 0 to disable
      "sphere_radius": 0.1,         # 指尖与指尖碰撞避免的球体半径
      "sphere_center": [0, -0.06, -0.185] # 指尖与指尖碰撞避免的球心位置
    },
  ],
  # gripper configurations, 0->right 1->left
  "grippers": [
    {
      "gripper_ip": "192.168.1.20", # 夹爪的IP地址 127.0.0.1
      "gripper_port": 1000,         # 夹爪的端口号
      "gripper_obs_latency": 0.01,  # 夹爪感知延迟
      "gripper_action_latency": 0.1 # 夹爪动作延迟
    },
    # {
    #   "gripper_ip": "192.168.0.27",
    #   "gripper_port": 1000, "gripper_obs_latency": 0.01, "gripper_action_latency": 0.1
    # }
  ],
  # # transformation right arm's base frame in left arm's base coordinate frame
  # # 描述右臂基坐标系在左臂基坐标系中的转换
  "tx_left_right": [
    [ 0.99996206,  0.00661996,  0.00566226, -0.01676012],
    [-0.00663261,  0.99997554,  0.0022186 , -0.60552492],
    [-0.00564743, -0.00225607,  0.99998151, -0.007277  ],
    [ 0.        ,  0.        ,  0.        ,  1.        ]
  ]
}
