{
  "robots": [
    {
      "robot_type": "realman",      # "robot_type": "ur5e",
      "robot_ip": "192.168.1.18",   # "robot_ip": "192.168.0.8",
      "robot_obs_latency": 0.0001,  # 机器人感知延迟 
      "robot_action_latency": 0.1,  # 机器人动作延迟
      "tcp_offset": 0.235,          # 工具中心点（TCP）的偏移量
      # table height for finger-table collision avoidance
      # -inf to disable
      "height_threshold": -0.024,   # 指尖与桌面碰撞避免的阈值
      # sphere collision primitive size and location for inter-gripper collision avoidance
      # 0 to disable
      "sphere_radius": 0.1,         # 指尖与指尖碰撞避免的球体半径
      "sphere_center": [0, -0.06, -0.185] # 指尖与指尖碰撞避免的球心位置
    },
  ],
}
